language: go
go:
 - "1.11.x"
 - "1.12.x"
 - "1.13.x"
before_install:
  - go get github.com/mattn/goveralls golang.org/x/tools/cmd/cover
install:
 - echo doing nothing
script:
 - goveralls -service=travis-ci
